version: "3.7"

services:
  frontend:
    container_name: doro_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
    - ./frontend/.env
