name: EC2 CI Action

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::808285223016:role/github-actions-role
          role-session-name: githubactions
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy on EC2 (full script)
        run: |
          CMD_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ubuntu/doro-study/backend",
              "export HOME=/home/ubuntu",
              "git config --global --add safe.directory /home/ubuntu/doro-study",
              "git stash --include-untracked",
              "git pull",
              "bun ci",
              "if pm2 describe \"bun dev\" > /dev/null; then pm2 restart \"bun dev\"; else pm2 start \"bun dev\"; fi",
              "pm2 save"
            ]' \
            --comment "Full deploy script" \
            --query "Command.CommandId" --output text)
      
          aws ssm wait command-executed --command-id $CMD_ID --instance-id ${{ secrets.INSTANCE_ID }}
      
          aws ssm get-command-invocation --command-id $CMD_ID --instance-id ${{ secrets.INSTANCE_ID }}
